# Generated by Django 4.0.6 on 2022-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.CharField(choices=[('Want to read', 'Want to read'), ('Reading', 'Reading'), ('Read', 'Read')], default='Want to read', max_length=12),
        ),
    ]
