# Generated by Django 4.0.6 on 2022-07-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
        migrations.AddField(
            model_name='tracker',
            name='status',
            field=models.CharField(choices=[('WTR', 'Want to read'), ('RING', 'Reading'), ('RD', 'Read')], default='WTR', max_length=4),
        ),
    ]
