# Generated by Django 4.0.6 on 2022-07-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_highlighted_book_language_book_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='style',
        ),
    ]
